version: '3.8'

services:

  frontend:
    build:
      context: ./frontend  # Path to the frontend directory
    command: npm start    # Adjust this based on your frontend setup
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app   # Mount the frontend code
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000

  backend:
    build:
      context: ./backend
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DOCKER_RUN=True
    depends_on:
      - db

  
  db:
    image: postgres:15.3
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
