# Generated by Django 4.2.5 on 2023-10-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0002_secretpassword_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretpassword',
            name='account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
